// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPredefinedServers() {
  return window['go']['main']['App']['GetPredefinedServers']();
}

export function SetSelectedServer(arg1) {
  return window['go']['main']['App']['SetSelectedServer'](arg1);
}

export function StartAutoSync(arg1) {
  return window['go']['main']['App']['StartAutoSync'](arg1);
}

export function SyncTime(arg1) {
  return window['go']['main']['App']['SyncTime'](arg1);
}
