// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPredefinedServers():Promise<Array<string>>;

export function SetSelectedServer(arg1:string):Promise<void>;

export function StartAutoSync(arg1:number):Promise<void>;

export function SyncTime(arg1:string):Promise<string>;
